export type SubjectDef = {
  name: string
  emoji: string
  level: ('BECE' | 'WASSCE')[]
  topics: string[]
}

export const SUBJECTS: SubjectDef[] = [
  {
    name: 'Mathematics',
    emoji: '📐',
    level: ['BECE', 'WASSCE'],
    topics: [
      'Number & Numeration',
      'Algebra',
      'Geometry',
      'Statistics',
      'Measurement',
      'Sets',
      'Quadratic Equations',
      'Indices & Logarithms',
      'Trigonometry',
      'Probability',
      'Vectors',
      'Matrices',
      'Sequences & Series',
      'Calculus',
    ],
  },
  {
    name: 'Integrated Science',
    emoji: '🔬',
    level: ['BECE'],
    topics: [
      'Living Things',
      'Matter & Change',
      'Energy',
      'Earth & Environment',
      'Human Body',
      'Photosynthesis',
      'Ecosystems',
      'Forces & Motion',
      'Chemical Reactions',
      'Reproduction',
    ],
  },
  {
    name: 'English Language',
    emoji: '📖',
    level: ['BECE', 'WASSCE'],
    topics: [
      'Comprehension',
      'Essay Writing',
      'Grammar & Usage',
      'Vocabulary',
      'Letter Writing',
      'Summary',
      'Oral English',
      'Narrative Writing',
    ],
  },
  {
    name: 'Social Studies',
    emoji: '🌍',
    level: ['BECE'],
    topics: [
      'Ghana History',
      'Government & Governance',
      'Physical Environment',
      'Culture & Identity',
      'Economic Development',
      'Citizenship',
      'West Africa',
      'Climate & Weather',
    ],
  },
  {
    name: 'Physics',
    emoji: '⚡',
    level: ['WASSCE'],
    topics: [
      'Mechanics',
      'Waves & Sound',
      'Optics & Light',
      'Electricity',
      'Magnetism',
      'Nuclear Physics',
      'Thermodynamics',
      'Measurements',
    ],
  },
  {
    name: 'Chemistry',
    emoji: '🧪',
    level: ['WASSCE'],
    topics: [
      'Atomic Structure',
      'Chemical Bonding',
      'Periodicity',
      'Acids Bases & Salts',
      'Organic Chemistry',
      'Electrochemistry',
      'Industrial Chemistry',
      'Stoichiometry',
    ],
  },
  {
    name: 'Biology',
    emoji: '🧬',
    level: ['WASSCE'],
    topics: [
      'Cell Biology',
      'Genetics & Heredity',
      'Ecology',
      'Human Physiology',
      'Plant Biology',
      'Microbiology',
      'Evolution',
      'Respiration',
    ],
  },
  {
    name: 'Economics',
    emoji: '📊',
    level: ['WASSCE'],
    topics: [
      'Demand & Supply',
      'Market Structures',
      'National Income',
      'Money & Banking',
      'International Trade',
      'Development Economics',
      'Public Finance',
      'Inflation',
    ],
  },
  {
    name: 'Religious & Moral Education',
    emoji: '🙏',
    level: ['BECE'],
    topics: [
      'God & Creation',
      'Moral Teachings',
      'Religious Leaders',
      'Prayer & Worship',
      'Festivals & Celebrations',
      'Golden Rule',
    ],
  },
  {
    name: 'Computing',
    emoji: '💻',
    level: ['BECE'],
    topics: [
      'Introduction to Computers',
      'Word Processing',
      'Spreadsheets',
      'Internet & Email',
      'Computer Hardware',
      'Programming Basics',
    ],
  },
  {
    name: 'Elective Maths',
    emoji: '🔢',
    level: ['WASSCE'],
    topics: [
      'Complex Numbers',
      'Polynomials',
      'Coordinate Geometry',
      'Differentiation',
      'Integration',
      'Statistics & Probability',
      'Vectors in 3D',
      'Permutation & Combination',
    ],
  },
  {
    name: 'Business Management',
    emoji: '💼',
    level: ['WASSCE'],
    topics: [
      'Business Organisation',
      'Management Functions',
      'Marketing',
      'Accounting Basics',
      'Human Resource',
      'Business Environment',
    ],
  },
  {
    name: 'Literature',
    emoji: '📜',
    level: ['WASSCE'],
    topics: [
      'Drama',
      'Poetry',
      'Prose Fiction',
      'Literary Devices',
      'African Literature',
      'Shakespearean Drama',
    ],
  },
  {
    name: 'History',
    emoji: '🏛️',
    level: ['WASSCE'],
    topics: [
      'Pre-Colonial Ghana',
      'Colonialism',
      'Nationalism & Independence',
      'Post-Independence Africa',
      'World Wars',
      'Cold War',
    ],
  },
  {
    name: 'Geography',
    emoji: '🗺️',
    level: ['WASSCE'],
    topics: [
      'Map Reading',
      'Physical Geography',
      'Human Geography',
      'Settlement',
      'Population',
      'Climate & Vegetation',
      'Economic Activities',
    ],
  },
  {
    name: 'General Science',
    emoji: '🔭',
    level: ['WASSCE'],
    topics: [
      'Scientific Method',
      'Energy & Power',
      'Environmental Science',
      'Health & Disease',
      'Agricultural Science',
      'Technology & Society',
    ],
  },
]

export function subjectsForLevel(level: 'BECE' | 'WASSCE') {
  return SUBJECTS.filter((s) => s.level.includes(level))
}
